name: Reporting

on:
  workflow_run:
    workflows: [ "__CI__" ]
    types:
      - completed

jobs:
  codecov:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.pull_requests[0].merged == true &&
      (
        github.event.workflow_run.pull_requests[0].base.ref == 'main' ||
        github.event.workflow_run.pull_requests[0].base.ref == 'tests'
      )

    strategy:
      fail-fast: false

      matrix:
        package: [ httio, rest ]

    runs-on: ubuntu-latest

    steps:
      - name: Download coverage artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: coverage
          path: ./coverage

      - name: Upload ${{ matrix.package }} coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          name: ${{ matrix.package }}
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/packages/${{ matrix.package }}/coverage/lcov.info
          flags: ${{ matrix.package }}
          fail_ci_if_error: true
