name: Testing

on:
  pull_request:
    branches-ignore:
      - 'releases/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 20.x, 22.x ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}

      - name: Find changed packages and dependencies
        id: changed
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const base = context.payload.pull_request.base.ref;
            const head = context.payload.pull_request.head.sha;

            const diff = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base,
              head
            });

            const files = diff.data.files.map(f => f.filename);

            const pkgs = [...new Set(
              files
                .filter(f => f.startsWith('packages/'))
                .map(f => f.split('/')[1])
            )];

            core.setOutput('packages', pkgs.join(' '));

      - name: Run tests per package
        run: |
          npm ci

          for pkg in ${{ steps.changed.outputs.packages }}; do
            echo "→ Processing package: $pkg"

            npm run lint --prefix packages/$pkg

            npm run build --prefix packages/$pkg

            npm test --prefix packages/$pkg
          done

        shell: bash
        env:
          CI: true
